"""add sources relation

Revision ID: a04d93bf1fc3
Revises: b6ec9d5ad22e
Create Date: 2026-06-18 14:20:41.039907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04d93bf1fc3'
down_revision: Union[str, Sequence[str], None] = 'b6ec9d5ad22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
